#!/usr/bin/env python3
print("<!DOCTYPE html>")
print()
print("<html lang=\"fr\">")
print("<head><title>CGI Test</title></head>")
print("<link rel=\"icon\" type=\"image/x-icon\ href=\"../../assets/images/favicon.ico\">")
print("<body style=\"text-align:center\">")
print("<nav style=\"padding:15px;\">")
print("<a href=\"../../index.html\" style=\"font-size: 20px;margin:1rem;width:150px;padding:5px;\">Home</a>")
print("</nav>")
print("<h1 style=\"font-size:30px;margin:3rem\">Hello World</h1>")
print("</body>")
print("</html>")