#!/usr/bin/env python3
print("Content-Type: text/html")
print()
print("<!DOCTYPE html>")
print()
print("<html lang=\"fr\">")
print("<head><title>CGI Test</title></head>")
print("<link rel=\"icon\" type=\"image/x-icon\ href=\"../../assets/images/favicon.ico\">")
print("<body>")
print("<h1>Hello World</h1>")
print("</body>")
print("</html>")